name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: win-x64
          - os: macos-latest
            platform: osx-arm64
    
    runs-on: ${{ matrix.os }}

    env:
      Solution_Name: vector-editor.sln                         # Actual solution name

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Add MSBuild to the PATH (Windows only)
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
      if: matrix.os == 'windows-latest'

    # Build the application
    - name: Build the application
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          dotnet build $Solution_Name --configuration ${{ matrix.configuration }}
        else
          dotnet build $Solution_Name --configuration ${{ matrix.configuration }}
        fi

    # Publish the application for specific runtime
    - name: Publish the application
      shell: bash
      run: |
        dotnet publish $Solution_Name \
          --configuration ${{ matrix.configuration }} \
          --runtime ${{ matrix.platform }} \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:PublishTrimmed=true \
          -o publish/${{ matrix.platform }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vector-editor-${{ matrix.platform }}
        path: publish/${{ matrix.platform }}
